spring.application.name=AI_RESUME_BUILDER

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

gemini.api.key=${GEMINI_API_KEY:AIzaSyDyQXUn3t2dpBg0FY5SdjeVU6m_CLwao5Y}
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent